baseURL = "https://marouanedaoudi.github.io/"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
title = "Marouane Daoudi"
theme = "blowfish"

[markup.goldmark.renderer]
  unsafe = true

[markup.goldmark.extensions.passthrough]
  enable = true
  [markup.goldmark.extensions.passthrough.delimiters]
    block = [['$$', '$$'], ['\[', '\]']]
    inline = [['$', '$'], ['\(', '\)']]

# --- MULTILINGUAL ---

[languages]

  [languages.en]
    languageCode = "en"
    languageName = "English"
    weight = 1
    [[languages.en.menu.main]]
      name = "Home"
      url = "/"
      weight = 10
    [[languages.en.menu.main]]
      name = "Notes"
      url = "/notes/"
      weight = 20
    [[languages.en.menu.main]]
      name = "Projects"
      url = "/projets/"
      weight = 30
    [[languages.en.menu.main]]
      name = "Contact"
      url = "mailto:marouane.daoudi@etu.umontpellier.fr"
      weight = 40

  [languages.fr]
    languageCode = "fr"
    languageName = "Français"
    weight = 2
    [[languages.fr.menu.main]]
      name = "Accueil"
      url = "/fr/"
      weight = 10
    [[languages.fr.menu.main]]
      name = "Notes"
      url = "/fr/notes/"
      weight = 20
    [[languages.fr.menu.main]]
      name = "Projets"
      url = "/fr/projets/"
      weight = 30
    [[languages.fr.menu.main]]
      name = "Contact"
      url = "mailto:marouane.daoudi@etu.umontpellier.fr"
      weight = 40

# --- PARAMS (communs) ---

[params]
  colorScheme = "ocean"
  defaultAppearance = "light"
  autoSwitchAppearance = false
  homepage.layout = "simple"
  homepage.showTitle = false
  homepage.showRecent = false
  article.math = true
  article.showDate = false
  article.showAuthor = false
  mathematics.enable = true
  footer.showPoweredBy = false
  footer.showTheme = false
  footer.showCopyright = true

[sitemap]
  changefreq = "weekly"
  priority = 0.5
