baseURL = "https://marouanedaoudi.github.io/"
languageCode = "fr"
title = "Marouane Daoudi"
theme = "blowfish"

[markup.goldmark.renderer]
  unsafe = true

[markup.goldmark.extensions.passthrough]
  enable = true
  [markup.goldmark.extensions.passthrough.delimiters]
    block = [['$$', '$$'], ['\[', '\]']]
    inline = [['$', '$'], ['\(', '\)']]

[menu]
  [[menu.main]]
    name = "Accueil"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "Notes"
    url = "/notes/"
    weight = 20
  [[menu.main]]
    name = "Projets"
    url = "/projets/"
    weight = 30
  [[menu.main]]
    name = "Contact"
    url = "mailto:marouane.daoudi@etu.umontpellier.fr"
    weight = 40

# --- CONFIGURATION PRINCIPALE ---
[sitemap]
  changefreq = "weekly"
  priority = 0.5

[params]
  colorScheme = "ocean"
  defaultAppearance = "dark"
  description = "Site personnel de Marouane Daoudi, étudiant en Master de Mathématiques Appliquées à l'Université de Montpellier. Projets en optimisation, statistique et data science."
  
  # Footer : On désactive les deux crédits
  footer.showPoweredBy = false
  footer.showTheme = false
  footer.showCopyright = true
  
  # Le reste de tes params...
  homepage.layout = "simple"
  homepage.showTitle = false
  homepage.showRecent = false

  article.math = true
  article.showDate = false
  article.showAuthor = false

  mathematics.enable = true